/*****************************************************************************
* Model: bomb4m.qm
* File:  ..\bomb4\src/bom4_a.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#include "qep_port.h"                /* the port of the QEP event processor */
#include "bomb4_a.h"                                   /* board support package */





/* @(/2/0) .................................................................*/
/* @(/2/0/3) ...............................................................*/
/* @(/2/0/3/0) */
QState Bomb4_initial(Bomb4 * const me, QEvt const * const e) {
    return Q_TRAN(&Bomb4_setting);
}
/* @(/2/0/3/1) .............................................................*/
QState Bomb4_setting(Bomb4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/3/1/0) */
        case ARM_SIG: {
            me->code = 0;
            status_ = Q_TRAN(&Bomb4_timing);
            break;
        }
        /* @(/2/0/3/1/1) */
        case DOWN_SIG: {
            if (me->timeout > 1) {
                --me->timeout;
                BSP_display(me->timeout);
            }
            status_ = Q_TRAN(&Bomb4_setting);
            break;
        }
        /* @(/2/0/3/1/2) */
        case UP_SIG: {
            if (me->timeout < 60) {
                ++me->timeout;
                BSP_display(me->timeout);
            }
            status_ = Q_TRAN(&Bomb4_setting);
            break;
        }
        default: {
            status_ = Q_IGNORED();
            break;
        }
    }
    return status_;
}
/* @(/2/0/3/2) .............................................................*/
QState Bomb4_timing(Bomb4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/3/2/0) */
        case UP_SIG: {
            me->code <<= 1;
            me->code |= 1;
            status_ = Q_TRAN(&Bomb4_timing);
            break;
        }
        /* @(/2/0/3/2/1) */
        case DOWN_SIG: {
            me->code <<= 1;
            status_ = Q_TRAN(&Bomb4_timing);
            break;
        }
        /* @(/2/0/3/2/2) */
        case TICK_SIG: {
            /* @(/2/0/3/2/2/0) */
            if (((TickEvt const *)e)->fine_time == 0) {
                --me->timeout;
                BSP_display(me->timeout);
                /* @(/2/0/3/2/2/0/0) */
                if (me->timeout <= 0) {
                    status_ = Q_TRAN(&Bomb4_BAM);
                }
                /* @(/2/0/3/2/2/0/1) */
                else if (me->code == me->defuse && me->timeout > 0) {
                    status_ = Q_TRAN(&Bomb4_setting);
                }
                /* @(/2/0/3/2/2/0/2) */
                else {
                    status_ = Q_TRAN(&Bomb4_timing);
                }
            }
            /* @(/2/0/3/2/2/1) */
            else {
                status_ = Q_TRAN(&Bomb4_timing);
            }
            break;
        }
        default: {
            status_ = Q_IGNORED();
            break;
        }
    }
    return status_;
}
/* @(/2/0/3/3) .............................................................*/
QState Bomb4_BAM(Bomb4 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/3/3) */
        case Q_ENTRY_SIG: {
            BSP_boom();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_IGNORED();
            break;
        }
    }
    return status_;
}



/* @(/2/1) .................................................................*/
void Bomb4_ctor(Bomb4 * me, uint8_t defuse) {
       QFsm_ctor(&me->super, (QStateHandler)&Bomb4_initial);/* superclass ctor */
        me->defuse = defuse;    /* the defuse code is assigned at instantiation */
}




