/*****************************************************************************
* Model: bomb4m.qm
* File:  ..\bomb4\src/bomb4_a.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/1) .................................................................*/
/*  Event driver Systems - University of Munich  - SS 2014 */


#include "bombqmbsp.h"


#define INIT_TIMEOUT   10

enum BombSignals {                          /* all signals for the Bomb FSM */
    UP_SIG = Q_USER_SIG,
    DOWN_SIG,
    ARM_SIG,
    TICK_SIG
};


/* @(/2/0) .................................................................*/
typedef struct Bomb4Tag {
/* protected: */
    QFsm super;

/* private: */
    uint16_t timeout;
    uint8_t code;

/* public: */
    uint8_t defuse;
} Bomb4;

/* protected: */
QState Bomb4_initial(Bomb4 * const me, QEvt const * const e);
QState Bomb4_setting(Bomb4 * const me, QEvt const * const e);
QState Bomb4_timing(Bomb4 * const me, QEvt const * const e);
QState Bomb4_BAM(Bomb4 * const me, QEvt const * const e);

/* @(/2/1) .................................................................*/
void Bomb4_ctor(Bomb4 * me, uint8_t defuse);

/* @(/1/0) .................................................................*/
typedef struct TickEvtTag {
/* protected: */
    QEvt super;

/* private: */
    uint8_t fine_time;
} TickEvt;



