/*****************************************************************************
* Model: blinky.qm
* File:  .\src/blinky2.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/2/0) ...............................................................*/
#include "blinky2.h"                                   /* board support package */





/* @(/2/0) .................................................................*/
/* @(/2/0/3) ...............................................................*/
/* @(/2/0/3/0) */
QState Blinky_initial(Blinky * const me, QEvt const * const e) {
    return Q_TRAN(&Blinky_Processing);
}
/* @(/2/0/3/1) .............................................................*/
QState Blinky_Processing(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/3/1/0) */
        case AD_READY_SIG: {
            /* @(/2/0/3/1/0/0) */
            if (me->AD_Old != me->AD_Value) {
                unsigned int n;
                unsigned int v;
                BSP_Disp_Bargraph(0, 1, (me->AD_Value/13));
                v = (5*(me->AD_Value)) >> 9;          /* Scale the Value                    */
                for (n = 0; n < 8; n++) {              /* Show the Value                     */
                    if (n < v) LED_On (n);              /* Turn LED On                        */
                    else       LED_Off(n);              /* Turn LED Off                       */
                }
                FSM_Post_Evt(BLINK_LED_LCD_SIG);
                status_ = Q_TRAN(&Blinky_Displaying);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /* @(/2/0/3/1/1) */
        case TICK_SIG: {
            FSM_Post_Evt(VT24_OUTPUT_SIG);
            status_ = Q_TRAN(&Blinky_Displaying);
            break;
        }
        default: {
            status_ = Q_IGNORED();
            break;
        }
    }
    return status_;
}
/* @(/2/0/3/2) .............................................................*/
QState Blinky_Displaying(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/2/0/3/2/0) */
        case BLINK_LED_LCD_SIG: {
            status_ = Q_TRAN(&Blinky_Processing);
            break;
        }
        /* @(/2/0/3/2/1) */
        case VT24_OUTPUT_SIG: {
            status_ = Q_TRAN(&Blinky_Processing);
            break;
        }
        default: {
            status_ = Q_IGNORED();
            break;
        }
    }
    return status_;
}



/* @(/2/1) .................................................................*/
void Blinky_ctor(Blinky* me) {
       QFsm_ctor(&me->super, (QStateHandler)&Blinky_initial);/* superclass ctor */
}
