/*****************************************************************************
* Model: blinky.qm
* File:  .\src/blinky2.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/2/2/1) ...............................................................*/
/*  Event driver Systems - University of Munich  - SS 2014 */

#ifndef BLINKY_2_H
#define BLINKY_2_H

#include "qep_port.h"                /* the port of the QEP event processor */
#include "bsp\bspblinky.h"


enum BlinkySignals {                          /* all signals for the Blinky FSM */
    AD_READY_SIG = Q_USER_SIG,
    TICK_SIG,
    BLINK_LED_LCD_SIG,
    VT24_OUTPUT_SIG,

    LENGTH_SIG
};


/* @(/2/0) .................................................................*/
typedef struct BlinkyTag {
/* protected: */
    QFsm super;

/* private: */
    short AD_Value;
    short AD_Print;
    short AD_Old;
} Blinky;

/* protected: */
QState Blinky_initial(Blinky * const me, QEvt const * const e);
QState Blinky_Processing(Blinky * const me, QEvt const * const e);
QState Blinky_Displaying(Blinky * const me, QEvt const * const e);

/* @(/2/1) .................................................................*/
void Blinky_ctor(Blinky* me);

/* @(/1/0) .................................................................*/
typedef struct ADEvtTag {
/* protected: */
    QEvt super;

/* private: */
    uint8_t fine_time;
} ADEvt;


#endif
